src/WebSystem.Mvc/ViewModels/SupplierViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebSystem.Mvc.ViewModels
{
    public class SupplierViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Informe o nome do fornecedor.")]
        [StringLength(100, ErrorMessage = "O nome do fornecedor deve conter entre {0} e {2} caracteres.", MinimumLength = 2)]
        [DisplayName("Nome do Fornecedor")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Informe a razão social do fornecedor.")]
        [StringLength(100, ErrorMessage = "A razão social do fornecedor deve conter entre {0} e {2} caracteres.", MinimumLength = 2)]
        [DisplayName("Razão Social")]
        public string CorporateName { get; set; }

        [Required(ErrorMessage = "Informe uma descrição para o fornecedor.")]
        [StringLength(255, ErrorMessage = "A descrição do fornecedor deve conter entre {0} e {2} caracteres.", MinimumLength = 2)]
        [DisplayName("Descrição")]
        public string Description { get; set; }

        [DisplayName("Situação")]
        public bool Active { get; set; }

        [DisplayName("Data de Cadastro")]
        public DateTime RegistrationDate { get; set; }

        [Required(ErrorMessage = "Informe o telefone do fornecedor.")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "O telefone está inválido.")]
        [DisplayName("Telefone")]
        public string Phone { get; set; }

        [StringLength(50, ErrorMessage = "O contato do fornecedor deve conter entre {0} e {2} caracteres.", MinimumLength = 2)]
        [DisplayName("Contato")]
        public string Contact { get; set; }

        public DocumentViewModel Document { get; set; }

        public EmailViewModel Email { get; set; }

        public AddressViewModel Address { get; set; }
    }
}

src/WebSystem.Mvc/Controllers/SupplierController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WebSystem.Mvc.Core.Interfaces;
using WebSystem.Mvc.Core.ValuesObject;
using WebSystem.Mvc.ViewModels;

namespace WebSystem.Mvc.Controllers
{
    public class SupplierController : BaseController
    {
        public readonly ISupplierRepository _supplierRepository;
        public readonly ISupplierService _supplierService;
        public readonly IMapper _mapper;

        public SupplierController(ISupplierRepository supplierRepository,
                                    ISupplierService supplierService,
                                    IMapper mapper,
                                    IHandleNotification handleNotification) : base(handleNotification)
        {
            _supplierRepository = supplierRepository;
            _supplierService = supplierService;
            _mapper = mapper;
        }


        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.GetAllAsync()));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            if (!ModelState.IsValid)
                return View(supplierViewModel);

            var email = _mapper.Map<Email>(supplierViewModel.Email);
            var document = _mapper.Map<Document>(supplierViewModel.Document);
            var address = _mapper.Map<Address>(supplierViewModel.Address);

            await _supplierService.ServiceSaveAsync(supplierViewModel.Name,
                                                    supplierViewModel.CorporateName,
                                                    supplierViewModel.Description,
                                                    supplierViewModel.Phone,
                                                    supplierViewModel.Contact,
                                                    email,
                                                    document,
                                                    address);
            
            return HasNotification() ? View(supplierViewModel) : RedirectToAction("Index");
        }


        public async Task<IActionResult> Update(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Guid id, SupplierViewModel supplierViewModel)
        {
            if (id != supplierViewModel.Id)
                return NotFound();

            ModelState.Remove("Address");

            if(!ModelState.IsValid)
                return BadRequest();

            var email = _mapper.Map<Email>(supplierViewModel.Email);
            var document = _mapper.Map<Document>(supplierViewModel.Document);

            await _supplierService.ServiceUpdateAsync(supplierViewModel.Id, supplierViewModel.Name, supplierViewModel.CorporateName, supplierViewModel.Description, supplierViewModel.Phone, supplierViewModel.Contact, email, document);

            return HasNotification() ? View(supplierViewModel) : RedirectToAction("Index");
        }

        public async Task<IActionResult> Activate(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        [HttpPost, ActionName("activate")]
        public async Task<IActionResult> ConfirmActivate(Guid id)
        {
            await _supplierService.ServiceActivateAsync(id);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Deactivate(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        [HttpPost, ActionName("deactivate")]
        public async Task<IActionResult> ConfirmDeactivate(Guid id)
        {
            await _supplierService.ServiceDeactivateAsync(id);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Address(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        [HttpPost, ActionName("address")]
        public async Task<IActionResult> UpdateAddress(Guid id, SupplierViewModel supplierViewModel)
        {
            if (id != supplierViewModel.Id) 
                return NotFound();

            ModelState.Remove("Name");
            ModelState.Remove("CorporateName");
            ModelState.Remove("Description");
            ModelState.Remove("Phone");
            ModelState.Remove("Contact");
            ModelState.Remove("Email");
            ModelState.Remove("Document");

            if (!ModelState.IsValid) return View(supplierViewModel);

            await _supplierService.ServiceUpdateAddressAsync(supplierViewModel.Id,supplierViewModel.Address.Street, supplierViewModel.Address.Number, supplierViewModel.Address.Neighborhood, supplierViewModel.Address.City, supplierViewModel.Address.State, supplierViewModel.Address.ZipCode);
            
            return HasNotification() ? View(supplierViewModel) : RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var supplierViewModel = await GetByIdAsync(id);

            return (supplierViewModel == null) ? NotFound() : View(supplierViewModel);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(Guid id)
        {
            await _supplierService.ServiceDeleteAsync(id);
            return RedirectToAction("Index");
        }



        #region Private_Methods

        private async Task<SupplierViewModel> GetByIdAsync(Guid id)
        {
            return _mapper.Map<SupplierViewModel>(await _supplierRepository.GetByIdAsync(id));
        }

        private bool HasNotification()
        {
            if (_handleNotification.HasNotification())
            {
                var notifications = _handleNotification.GetNotifications();
                foreach (var notification in notifications)
                {
                    AddErrorsModelState(notification.Message);
                }
                return true;
            }

            return false;
        }

        #endregion
    }
}

src/WebSystem.Mvc/Extensions/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebSystem.Mvc.Core.Interfaces;

namespace WebSystem.Mvc.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly IHandleNotification _handleNotification;

        public SummaryViewComponent(IHandleNotification handleNotification)
        {
            _handleNotification = handleNotification;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifications = await Task.FromResult(_handleNotification.GetNotifications());
            notifications.ForEach(notification => ViewData.ModelState.AddModelError(string.Empty, notification.Message));
            return View();
        }
    }
}

src/WebSystem.Mvc/Views/Supplier/Activate.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Ativar o fornecedor";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Ativação do Fronecedor</h3>
        </div>
        <div class="card-body">
            @{
                if (Model.Active)
                {
                    <div class="container justify-content-center">
                        <div class="alert alert-primary text-center">
                            <h3>Ops! O fornecedor <strong>@Model.Name</strong> já está ATIVO.</h3>
                            <a class="btn btn-sm btn-danger" asp-action="Index">Voltar</a>
                        </div>
                    </div>
                }
                else
                {
                    <form asp-action="Activate">
                        <div class="m-2">
                            <label asp-for="Name" class="form-label"></label>
                            <input asp-for="Name" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <label asp-for="CorporateName" class="form-label"></label>
                            <input asp-for="CorporateName" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <label asp-for="Document.Number" class="form-label" title="Documento">Número do documento</label>
                            <input asp-for="Document.Number" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <input type="submit" class="btn btn-sm btn-success me-2" title="Ativar" />
                            <a class="btn btn-sm btn-danger" asp-action="Index">Cancelar</a>
                        </div>
                    </form>
                }
            }
        </div>
    </div>
</div>

src/WebSystem.Mvc/Views/Supplier/Address.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Atualizar Endereço";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Atualização do Endereço do Fornecedor</h3>
        </div>
        <div class="card-body">
            <form asp-action="Address">
                <vc:summary></vc:summary>
                <div class="m-2">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control form-control-sm form-text text-dark" />
                </div>
                <div class="m-2">
                    <label asp-for="Address.Street" class="form-label"></label>
                    <input asp-for="Address.Street" class="form-control form-control-sm form-text text-dark" placeholder="Nome da rua" />
                    <span asp-validation-for="Address.Street" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.Number" class="form-label"></label>
                    <input asp-for="Address.Number" class="form-control form-control-sm form-text text-dark" placeholder="Número do endereço" />
                    <span asp-validation-for="Address.Number" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.Neighborhood" class="form-label"></label>
                    <input asp-for="Address.Neighborhood" class="form-control form-control-sm form-text text-dark" placeholder="Nome do bairro" />
                    <span asp-validation-for="Address.Neighborhood" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.City" class="form-label" title="Cidade">Cidade</label>
                    <input asp-for="Address.City" class="form-control form-control-sm form-text text-dark" placeholder="Nome da cidade" />
                    <span asp-validation-for="Address.City" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label for="state" class="form-label"></label>
                    <input asp-for="Address.State" class="form-control form-control-sm form-text text-dark" placeholder="Nome do estado" />
                    <span asp-validation-for="Address.State" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.ZipCode" class="form-label"></label>
                    <input asp-for="Address.ZipCode" class="form-control form-control-sm form-text text-dark" placeholder="Número do CEP" />
                    <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <input type="submit" class="btn btn-sm btn-success btn-form me-2" title="Atualizar" />
                    <a class="btn btn-sm btn-danger btn-form" asp-action="Index">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

src/WebSystem.Mvc/Views/Supplier/Create.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Novo fornecedor";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Novo Fornecedor</h3>
        </div>
        <div class="card-body">
            <form asp-action="Create">
                <vc:summary></vc:summary>
                <div class="m-2">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control form-control-sm form-text text-dark" placeholder="Nome do fornecedor" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="CorporateName" class="form-label"></label>
                    <input asp-for="CorporateName" class="form-control form-control-sm form-text text-dark" placeholder="Razão Social do fornecedor" />
                    <span asp-validation-for="CorporateName" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-control form-control-sm form-text text-dark" placeholder="Nome do fornecedor" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Phone" class="form-label"></label>
                    <input asp-for="Phone" class="form-control form-control-sm form-text text-dark" placeholder="Telefone do fornecedor" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Contact" class="form-label"></label>
                    <input asp-for="Contact" class="form-control form-control-sm form-text text-dark" placeholder="Nome de contato" />
                    <span asp-validation-for="Contact" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Document.Type" class="form-label"></label>
                    <select class="form-select form-select-sm" aria-label="DocumentType" asp-for="Document.Type">
                        <option selected>Escolha uma opção</option>
                        <option value="1">CPF</option>
                        <option value="2">CNPJ</option>
                    </select>
                    <span asp-validation-for="Document.Type" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Document.Number" class="form-label"></label>
                    <input asp-for="Document.Number" class="form-control form-control-sm form-text text-dark" placeholder="Número do documento" />
                    <span asp-validation-for="Document.Number" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email.EmailAddress" class="form-control form-control-sm form-text text-dark" placeholder="Endereço de e-mail" />
                    <span asp-validation-for="Email.EmailAddress" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.Street" class="form-label"></label>
                    <input asp-for="Address.Street" class="form-control form-control-sm form-text text-dark" placeholder="Nome da rua" />
                    <span asp-validation-for="Address.Street" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.Number" class="form-label"></label>
                    <input asp-for="Address.Number" class="form-control form-control-sm form-text text-dark" placeholder="Número do endereço" />
                    <span asp-validation-for="Address.Number" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.Neighborhood" class="form-label"></label>
                    <input asp-for="Address.Neighborhood" class="form-control form-control-sm form-text text-dark" placeholder="Nome do bairro" />
                    <span asp-validation-for="Address.Neighborhood" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.City" class="form-label"></label>
                    <input asp-for="Address.City" class="form-control form-control-sm form-text text-dark" placeholder="Nome da cidade" />
                    <span asp-validation-for="Address.City" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label for="state" class="form-label" title="Estado">Estado</label>
                    <input asp-for="Address.State" class="form-control form-control-sm form-text text-dark" placeholder="Nome do estado" />
                    <span asp-validation-for="Address.State" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Address.ZipCode" class="form-label"></label>
                    <input asp-for="Address.ZipCode" class="form-control form-control-sm form-text text-dark" placeholder="Número do CEP" />
                    <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <input type="submit" class="btn btn-sm btn-success btn-form m2-2" title="Cadastrar" />
                    <a class="btn btn-sm btn-danger btn-form" asp-action="Index">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

src/WebSystem.Mvc/Views/Supplier/Deactivate.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Desativar o fornecedor";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Desativação do Fronecedor</h3>
        </div>
        <div class="card-body">
            @{
                if (!Model.Active)
                {
                    <div class="container justify-content-center">
                        <div class="alert alert-primary text-center">
                            <h3>Ops! O fornecedor <strong>@Model.Name</strong> já está INATIVO.</h3>
                            <a class="btn btn-sm btn-danger" asp-action="Index">Voltar</a>
                        </div>
                    </div>
                }
                else
                {
                    <form asp-action="Deactivate">
                        <div class="m-2">
                            <label asp-for="Name" class="form-label"></label>
                            <input asp-for="Name" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <label asp-for="CorporateName" class="form-label"></label>
                            <input asp-for="CorporateName" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <label asp-for="Document.Number" class="form-label" title="Documento">Número do documento</label>
                            <input asp-for="Document.Number" class="form-control form-control-sm form-text text-dark" readonly="readonly" />
                        </div>

                        <div class="m-2">
                            <input type="submit" class="btn btn-sm btn-success me-2" title="Desativar" />
                            <a class="btn btn-sm btn-danger" asp-action="Index">Cancelar</a>
                        </div>
                    </form>
                }
            }

        </div>
    </div>
</div>

src/WebSystem.Mvc/Views/Supplier/Delete.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Exclusão de fornecedor";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Exclusão do Fornecedor</h3>
        </div>
        <div class="card-body">
            <form asp-action="Delete">
                <div class="m-2">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control form-control-sm form-text text-dark" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="m-2">
                    <input type="submit" class="btn btn-sm btn-success btn-form me-2" title="Deletar" />
                    <a class="btn btn-sm btn-danger btn-form" asp-action="Index">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

src/WebSystem.Mvc/Views/Supplier/Index.cshtml
@model IEnumerable<SupplierViewModel>;

@{
    ViewData["Title"] = "Lista de fornecedores";
}

<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="p-0 my-3 d-flex justify-content-start">
                <h1 class="display-4">Fornecedores</h1>
            </div>
        </div>
        <div class="col-6">
            <div class="p-0 my-4 d-flex justify-content-end">
                <a class="btn btn-primary btn-sm me-2" asp-action="Create">Novo Fornecedor</a>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive table-responsive-sm">
    @{
        if (!Model.Any())
        {
            <div class="container justify-content-center">
                <div class="alert alert-primary text-center">
                    <h3>Ops! Nenhum registro encontrado. Caso queira, adicione um fornecedor clicando no botão <strong>Novo Fornecedor</strong></h3>
                </div>
            </div>
        }
        else
        {
            <table class="table table-sm">
                <thead class="table-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th>@Html.DisplayNameFor(model => model.CorporateName)</th>
                        <th>@Html.DisplayNameFor(model => model.Document.Number)</th>
                        <th>@Html.DisplayNameFor(model => model.Email)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => item.Name)</td>
                            <td>@Html.DisplayFor(model => item.CorporateName)</td>
                            <td>@Html.DisplayFor(model => item.Document.Number)</td>
                            <td>@Html.DisplayFor(model => item.Email.EmailAddress)</td>
                            <td>
                                <div class="d-flex justify-content-end">
                                    <div class="justify-content-around">
                                        <a class="btn btn-success btn-sm" asp-action="Details" asp-route-id="@item.Id" title="Detalhes"><i class="fas fa-search"></i></a>
                                        <a class="btn btn-warning btn-sm" asp-action="Update" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                                        <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id" title="Excluir"><i class="fas fa-trash"></i></a>
                                        <a class="btn btn-secondary btn-sm" asp-action="Address" asp-route-id="@item.Id" title="Atualizar Endereço do Fornecedor"><i class="fas fa-map-marked"></i></a>
                                        <a class="btn btn-primary btn-sm" asp-action="Activate" asp-route-id="@item.Id" title="Ativar Fornecedor"><i class="fas fa-thumbs-up"></i></a>
                                        <a class="btn btn-primary btn-sm" asp-action="Deactivate" asp-route-id=@item.Id title="Desativar Fornecedor"><i class="fas fa-thumbs-down"></i></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
</div>

src/WebSystem.Mvc/Views/Supplier/Update.cshtml
@model SupplierViewModel;

@{
    ViewData["Title"] = "Atualização do fornecedor";
}

<div class="d-flex justify-content-center mt-4">
    <div class="card mx-auto">
        <div class="card-header">
            <h3 class="display-5">Atualização do Fornecedor</h3>
        </div>
        <div class="card-body">
            <form asp-action="Update">
                <vc:summary></vc:summary>
                <div class="m-2">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control form-control-sm form-text text-dark" placeholder="Nome do fornecedor" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="CorporateName" class="form-label"></label>
                    <input asp-for="CorporateName" class="form-control form-control-sm form-text text-dark" placeholder="Razão Social do fornecedor" />
                    <span asp-validation-for="CorporateName" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-control form-control-sm form-text text-dark" placeholder="Nome do fornecedor" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Phone" class="form-label"></label>
                    <input asp-for="Phone" class="form-control form-control-sm form-text text-dark" placeholder="Telefone do fornecedor" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Contact" class="form-label"></label>
                    <input asp-for="Contact" class="form-control form-control-sm form-text text-dark" placeholder="Nome de contato" />
                    <span asp-validation-for="Contact" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Document.Type" class="form-label"></label>
                    <select class="form-select form-select-sm" aria-label="DocumentType" asp-for="Document.Type">
                        <option selected>Escolha uma opção</option>
                        <option value="1">CPF</option>
                        <option value="2">CNPJ</option>
                    </select>
                    <span asp-validation-for="Document.Type" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Document.Number" class="form-label"></label>
                    <input asp-for="Document.Number" class="form-control form-control-sm form-text text-dark" placeholder="Número do documento" />
                    <span asp-validation-for="Document.Number" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email.EmailAddress" class="form-control form-control-sm form-text text-dark" placeholder="Endereço de e-mail" />
                    <span asp-validation-for="Email.EmailAddress" class="text-danger"></span>
                </div>

                <div class="m-2">
                    <input type="submit" class="btn btn-sm btn-success btn-form me-2" title="Atualizar" />
                    <a class="btn btn-sm btn-danger btn-form" asp-action="Index">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>